Utkarsha/fix/responsive design
binary-com/deriv-api-docs pull request #117
Opened 2023-04-24 13:27 UTC by utkarsha-deriv

2023-04-25 06:18 UTC, mohsen-deriv requested changes

2023-04-25 06:18 UTC, mohsen-deriv commented on src/features/Home/Benefits/Benefits.module.scss
> +        // @media screen and (max-width: 992px) {
please remove these, thanks :pray:

2023-04-25 06:18 UTC, mohsen-deriv commented on src/styles/index.scss
> +  .c-PJLV-brTEFi-type-subtitle-2 {
this will change, please use another class name

2023-04-25 06:18 UTC, mohsen-deriv commented on src/features/Home/HeroHeader/HeroHeader.module.scss
> +      // align-items: baseline;
please remove this

2023-04-25 06:57 UTC, matin-deriv submitted a review, later dismissed

2023-04-26 08:22 UTC, mohsen-deriv submitted a review, later dismissed

2023-04-27 13:03 UTC, merged