feat: added testcase and popup
binary-com/deriv-api-docs pull request #187
Opened 2023-06-14 09:42 UTC by utkarsha-deriv

2023-06-16 07:48 UTC, mohsen-deriv requested changes

2023-06-16 07:58 UTC, mohsen-deriv approved these changes

2023-06-16 07:58 UTC, mohsen-deriv commented on src/features/dashboard/components/Dialogs/TokenCreationDialogSuccess/index.tsx
> +    <Modal defaultOpen onOpenChange={onOpenChange}>
my bad, a chrome extension messed up my page.

2023-06-21 09:13 UTC, matin-deriv approved these changes

2023-06-28 08:37 UTC, hubert-deriv reviewed
Please resolve the conflicts so that I can merge

2023-07-03 10:12 UTC, mohsen-deriv approved these changes

2023-07-04 09:49 UTC, sanjam-deriv submitted a review, later dismissed

2023-07-20 12:30 UTC, hubert-deriv requested changes

2023-07-20 12:30 UTC, hubert-deriv commented on src/features/dashboard/components/ApiTokenForm/api-token.form.tsx
> +      setToggleModal(!is_toggle);
I think `setToggleModal(prev => !prev)` is a nicer way of handling it. If setting your state is dependent on your previous state, you should use this prev (or prevState) method.

2023-07-20 12:30 UTC, hubert-deriv submitted a review, later dismissed

2023-07-21 06:38 UTC, matin-deriv approved these changes

2023-07-31 14:49 UTC, merged