feat: added restrictions appname
binary-com/deriv-api-docs pull request #200
Opened 2023-07-03 13:41 UTC by utkarsha-deriv

2023-07-10 07:23 UTC, matin-deriv submitted a review, later dismissed
LGTM

2023-07-11 02:46 UTC, matin-deriv approved these changes

2023-07-11 14:58 UTC, hubert-deriv approved these changes

2023-07-18 03:54 UTC, matin-deriv submitted a review, later dismissed

2023-07-24 10:38 UTC, hubert-deriv requested changes

2023-07-24 10:38 UTC, hubert-deriv commented on src/features/dashboard/components/AppForm/index.tsx
> +          {button_text}
Perhaps, we can remove the `button_text` prop and instead show the correct button text this way:

`is_update_mode ? 'Update Application' : 'Register Application'`

2023-07-24 11:27 UTC, hubert-deriv approved these changes

2023-07-26 11:18 UTC, sanjam-deriv approved these changes

2023-07-31 14:47 UTC, hubert-deriv approved these changes

2023-07-31 14:47 UTC, merged