chore: add route parameter to loginURL
binary-com/deriv-api-docs pull request #227
Opened 2023-07-31 06:19 UTC by utkarsha-deriv

2023-07-31 07:49 UTC, sanjam-deriv submitted a review, later dismissed

2023-07-31 08:35 UTC, hubert-deriv requested changes
Looks good so far but we need to escape the slashes from the pathname and change them to `%2F`. So for example instead of `my/path/name` it should be `my%2Fpath%2Fname`

You should be able to do this with the [replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) method. Please have a look.

2023-07-31 11:11 UTC, hubert-deriv approved these changes

2023-09-11 07:45 UTC, sanjam-deriv commented
Closing this because the changes were already pulled and the branch is no longer required

2023-09-11 07:45 UTC, closed without merging