[FEQ] Jim/FEQ-1090/separate docker and kubernetes notification
binary-com/deriv-api-docs pull request #275
Opened 2023-12-20 08:41 UTC by jim-deriv

## Changes
- Separated `Docker` and `Kubernetes` Status notification from `Cloudflare Pages` deployment slack notification

2023-12-21 12:47 UTC, yaswanth-deriv approved these changes

2023-12-26 02:27 UTC, ameerul-deriv approved these changes

2023-12-26 03:12 UTC, niloofar-deriv approved these changes

2024-01-02 04:17 UTC, ali-hosseini-deriv approved these changes

2024-01-02 04:25 UTC, ali-hosseini-deriv requested changes

2024-01-02 04:25 UTC, ali-hosseini-deriv commented on .github/workflows/release_staging.yml
> +      - name: Send Slack Notification
we dont need to have slack notification for staging releases, please revert the changes on the staging workflow

2024-01-02 05:21 UTC, ali-hosseini-deriv approved these changes

2024-01-02 05:22 UTC, merged