Hubert / Install setup linaria
binary-com/deriv-api-docs pull request #5
Opened 2022-12-05 16:06 UTC by hubert-deriv

2022-12-06 08:36 UTC, michio-rework requested changes

2022-12-06 08:36 UTC, michio-rework commented on package.json
> +    "@linaria/babel-preset": "^4.3.1",
please move these to `devDependencies`, thanks thanks :pray:

2022-12-06 08:36 UTC, michio-rework commented on package.json
> +    "@linaria/babel-preset": "^4.3.1",
`@linaria/babel-preset`, `@linaria/core` `@linaria/react`

2022-12-06 08:36 UTC, michio-rework commented on package.json
> +    "@linaria/webpack-loader": "^4.1.9",
please move this to `devDependencies`, thanks thanks :pray:

2022-12-06 08:36 UTC, michio-rework commented on package.json
> +    "babel-loader": "^9.1.0",
please remove `babel-loader`, `css-loader`, `file-loader`, `mini-css-extract-plugin`, `webpack`, `webpack-cli`, `webpack-dev-server`, we don't need them, thanks thanks :pray:

2022-12-07 11:46 UTC, closed without merging

2022-12-07 11:47 UTC, hubert-deriv commented
Creating new pr here: https://github.com/binary-com/deriv-api-docs/pull/7

due to package lock merge conflicts.