Utkarsha/91053/card view design change
binary-com/deriv-api-docs pull request #75
Opened 2023-03-27 07:50 UTC by utkarsha-deriv

2023-03-27 10:11 UTC, mohsen-deriv requested changes

2023-03-27 10:11 UTC, mohsen-deriv commented on src/styles/index.scss
> +  box-shadow: 0px 12px 16px -4px rgba(14, 14, 14, 0.08), 0px 4px 6px -2px rgba(14, 14, 14, 0.03) !important;
please update your selector and don't use `!important`, thanks :pray:

2023-03-27 10:11 UTC, mohsen-deriv commented on src/styles/index.scss
> +  line-height: 2.25rem;
use rem function

2023-03-27 10:11 UTC, mohsen-deriv commented on src/styles/index.scss
> +  line-height: 1.5rem;
use rem function

2023-03-27 10:11 UTC, mohsen-deriv commented on src/styles/index.scss
> +  top: 1rem;
use rem function

2023-03-28 08:05 UTC, sanjam-deriv commented on src/theme/DocCard/styles.module.css
> +  top: 0.8rem;
use rem function

2023-03-28 08:05 UTC, sanjam-deriv commented on src/theme/DocCard/styles.module.css
> +  box-shadow: 0 3px 6px 0 rgb(0 0 0 / 20%);
Change to rem

2023-03-28 08:05 UTC, sanjam-deriv commented on src/theme/DocCard/styles.module.css
> +  margin-top: 8px;
use rem()  for sizing scss

2023-03-28 11:38 UTC, sanjam-deriv approved these changes

2023-03-29 00:22 UTC, mohsen-deriv approved these changes

2023-03-29 00:23 UTC, merged